// Change the name of this to ContractAddresses.js and set your locally deployed addresses
const contractAddresses = {
  // GANACHE
  GANACHE_GAME_REGISTRY: "",
  GANACHE_HEXPLORATION_BOARD: "",
  GANACHE_HEXPLORATION_CONTROLLER: "",
  GANACHE_GAME_SUMMARY: "",
  GANACHE_HEXPLORATION_QUEUE: "",
  GANACHE_HEXPLORATION_GAMEPLAY: "",
  // MUMBAI
  MUMBAI_GAME_REGISTRY: "",
  MUMBAI_HEXPLORATION_BOARD: "",
  MUMBAI_HEXPLORATION_CONTROLLER: "",
  MUMBAI_GAME_SUMMARY: "",
  MUMBAI_HEXPLORATION_QUEUE: "",
  MUMBAI_HEXPLORATION_GAMEPLAY: "",
  // POLYGON
  POLYGON_GAME_REGISTRY: "",
  POLYGON_HEXPLORATION_BOARD: "",
  POLYGON_HEXPLORATION_CONTROLLER: "",
  POLYGON_GAME_SUMMARY: "",
  POLYGON_HEXPLORATION_QUEUE: "",
  POLYGON_HEXPLORATION_GAMEPLAY: "",
  // BINANCE TEST
  BINANCE_TEST_GAME_REGISTRY: "",
  BINANCE_TEST_HEXPLORATION_BOARD: "",
  BINANCE_TEST_HEXPLORATION_CONTROLLER: "",
  BINANCE_TEST_GAME_SUMMARY: "",
  BINANCE_TEST_HEXPLORATION_QUEUE: "",
  BINANCE_TEST_HEXPLORATION_GAMEPLAY: "",
  // BINANCE
  BINANCE_GAME_REGISTRY: "",
  BINANCE_HEXPLORATION_BOARD: "",
  BINANCE_HEXPLORATION_CONTROLLER: "",
  BINANCE_GAME_SUMMARY: "",
  BINANCE_HEXPLORATION_QUEUE: "",
  BINANCE_HEXPLORATION_GAMEPLAY: "",
};

module.exports = contractAddresses;
